[env]
TERM = "screen-256color"

[general]
live_config_reload = true

[font]
normal = { family = "M+CodeLat50 Nerd Font", style = "Regular" }
size = 12

[window]
dynamic_title = false
blur = true
padding = { x = 3, y = 3 }
dynamic_padding = true

# One Dark

# Default colors
[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

# Normal colors
[colors.normal]
black = "#1e2127"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

# Bright colors
[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

# Theme reserve

# # Gruvbox Dark Theme
# [colors.primary]
# background = '#282828'
# foreground = '#ebdbb2'
#
# [colors.normal]
# black   = '#282828'
# red     = '#cc241d'
# green   = '#98971a'
# yellow  = '#d79921'
# blue    = '#458588'
# magenta = '#b16286'
# cyan    = '#689d6a'
# white   = '#a89984'
#
# [colors.bright]
# black   = '#928374'
# red     = '#fb4934'
# green   = '#b8bb26'
# yellow  = '#fabd2f'
# blue    = '#83a598'
# magenta = '#d3869b'
# cyan    = '#8ec07c'
# white   = '#ebdbb2'
