[env]
TERM = "screen-256color"

[general]
live_config_reload = true

[font]
normal = {family = "M+CodeLat50 Nerd Font", style = "Regular"}
size = 13.5

[window]
dynamic_title = false
blur = true
padding = { x = 3, y = 3 }
dynamic_padding = true

# Gruvbox Dark Theme
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
